networks:
  url-shortener:
    name: url-shortener
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.1.0/24

volumes:
  db_data:
  pg_data:

services:
  db:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "url-shortener"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database_schema.sql:/docker-entrypoint-initdb.d/database_schema.sql
    healthcheck:
      test: pg_isready
    # uncomment if you need to run tests
    ports:
      - "5432:5432"
    networks:
      url-shortener:
        ipv4_address: 172.26.1.2

  pg-admin:
    image: dpage/pgadmin4:latest
    networks:
      url-shortener:
        ipv4_address: 172.26.1.3
    environment:
      PGADMIN_DEFAULT_EMAIL: "pg_admin_address@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "dont tell anyone"
    # enter http://127.0.0.1:21377 in your web browser to enter the admin panel so you can check the database content
    ports:
      - "21377:80"
    volumes:
      - pg_data:/var/lib/pgadmin

  web-server:
    image: tmp
    build:
      dockerfile: ./Dockerfile
    environment:
      http_bind_address: "http://0.0.0.0:2137"
      domain_name: "http://127.0.0.1:2137"
      web_files_directory: /url-shortener/web
      main_website_filename: main.html
      POSTGRES_DB: "url-shortener"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_ADDRESS: "172.26.1.2"
    ports:
      - 2137:2137
      #EXPOSE PORT 80 ON YOUR ROUTER AND FORWARD TRAFFIC TO DEVICE TO MAKE THE SERVICE PUBLIC
    networks:
      url-shortener:
        ipv4_address: 172.26.1.4
    depends_on:
      db:
        condition: service_healthy

  reverse-proxy:
    image: caddy:latest
    networks:
      url-shortener:
        ipv4_address: 172.26.1.5